version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20 # Specify Node.js version
    commands:
      - echo Installing dependencies...
      - npm ci # Faster alternative to npm install
  pre_build:
    commands:
      - echo Running pre-build steps...
      - echo Checking code style and linting...
      - npm run lint || echo "Linting failed or skipped"
      - echo Running unit tests (if any)...
      - npm test || echo "Tests failed or skipped"
  build:
    commands:
      - echo Building the app...
      - npm run build
  post_build:
    commands:
      - echo Build process complete!

cache:
  paths:
    - node_modules/**/*

artifacts:
  files:
    - 'build/**/*' # Include only the build directory in artifacts
