version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo Installing Node.js version 20 ...
      - npm install
  pre_build:
    commands:
      - echo Installing dependencies...
      # Removed npm install here as it is redundant
  build:
    commands:
      - echo Building the app...
      - npm run build

artifacts:
  files:
    - '**/*'
  discard-paths: no
  base-directory: build
