version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20 # Specify Node.js version
    commands:
      - echo Installing dependencies...
      - npm install
  pre_build:
    commands:
      - echo Running linting or pre-build tests...
      - npm run lint || echo "Linting skipped or failed" # Ensures the process continues even if linting fails
  build:
    commands:
      - echo Building the app...
      - npm run build
  post_build:
    commands:
      - echo Running post-build steps...
      - npm test || echo "Tests skipped or failed" # Avoid build termination if tests fail
      - echo Build complete!

artifacts:
  files:
    - '**/*' # Include all files in the build artifact
  discard-paths: no # Retain the original directory structure in artifacts
  base-directory: build # Set 'build' as the base directory for artifacts
